quests = {
    "q1": {
        "id": "q1",
        "titulo": "A Cripta Esquecida",
        "descricao": "Explore a cripta ao norte e elimine os mortos-vivos que assombram os aldeões.",
        "dificuldade": "Fácil",
        "cor_dificuldade": "green",
        "recompensa_xp": 300,
        "recompensa_ouro": 50,
        "status": "available",
        "id_heroi": None,
        "aceito_em": None,
        "concluido_em": None,
        "icone": "💀",
    },
    "q2": {
        "id": "q2",
        "titulo": "O Grimório Perdido",
        "descricao": "Encontre o grimório do arquimago Valdris nas ruínas da torre encantada.",
        "dificuldade": "Médio",
        "cor_dificuldade": "yellow",
        "recompensa_xp": 600,
        "recompensa_ouro": 120,
        "status": "available",
        "id_heroi": None,
        "aceito_em": None,
        "concluido_em": None,
        "icone": "📖",
    },
    "q3": {
        "id": "q3",
        "titulo": "Dragão de Gelo de Vorheim",
        "descricao": "O dragão Vorheim aterroriza o reino. Apenas o mais corajoso pode enfrentá-lo.",
        "dificuldade": "Épico",
        "cor_dificuldade": "red",
        "recompensa_xp": 2000,
        "recompensa_ouro": 500,
        "status": "available",
        "id_heroi": None,
        "aceito_em": None,
        "concluido_em": None,
        "icone": "🐉",
    },
    "q4": {
        "id": "q4",
        "titulo": "Poções para a Aldeia",
        "descricao": "A aldeia de Mireth precisa de poções de cura. Colete ervas e entregue ao curandeiro.",
        "dificuldade": "Fácil",
        "cor_dificuldade": "green",
        "recompensa_xp": 150,
        "recompensa_ouro": 30,
        "status": "available",
        "id_heroi": None,
        "aceito_em": None,
        "concluido_em": None,
        "icone": "🧪",
    },
}
