# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"f\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0c\n\x04tipo\x18\x03 \x01(\t\x12\x10\n\x08raridade\x18\x04 \x01(\t\x12\x12\n\nquantidade\x18\x05 \x01(\x05\x12\x10\n\x08heroi_id\x18\x06 \x01(\t\"j\n\x14\x41\x64icionarItemRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x10\n\x08raridade\x18\x03 \x01(\t\x12\x12\n\nquantidade\x18\x04 \x01(\x05\x12\x10\n\x08heroi_id\x18\x05 \x01(\t\"+\n\x17ListarInventarioRequest\x12\x10\n\x08heroi_id\x18\x01 \x01(\t\"[\n\x12InventarioResponse\x12\x10\n\x08heroi_id\x18\x01 \x01(\t\x12\x1e\n\x05itens\x18\x02 \x03(\x0b\x32\x0f.inventory.Item\x12\x13\n\x0btotal_itens\x18\x03 \x01(\x05\"\"\n\x14\x43onsultarItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x12RemoverItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x13RemoverItemResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2\xbd\x02\n\x10InventoryService\x12\x41\n\rAdicionarItem\x12\x1f.inventory.AdicionarItemRequest\x1a\x0f.inventory.Item\x12U\n\x10ListarInventario\x12\".inventory.ListarInventarioRequest\x1a\x1d.inventory.InventarioResponse\x12\x41\n\rConsultarItem\x12\x1f.inventory.ConsultarItemRequest\x1a\x0f.inventory.Item\x12L\n\x0bRemoverItem\x12\x1d.inventory.RemoverItemRequest\x1a\x1e.inventory.RemoverItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=30
  _globals['_ITEM']._serialized_end=132
  _globals['_ADICIONARITEMREQUEST']._serialized_start=134
  _globals['_ADICIONARITEMREQUEST']._serialized_end=240
  _globals['_LISTARINVENTARIOREQUEST']._serialized_start=242
  _globals['_LISTARINVENTARIOREQUEST']._serialized_end=285
  _globals['_INVENTARIORESPONSE']._serialized_start=287
  _globals['_INVENTARIORESPONSE']._serialized_end=378
  _globals['_CONSULTARITEMREQUEST']._serialized_start=380
  _globals['_CONSULTARITEMREQUEST']._serialized_end=414
  _globals['_REMOVERITEMREQUEST']._serialized_start=416
  _globals['_REMOVERITEMREQUEST']._serialized_end=448
  _globals['_REMOVERITEMRESPONSE']._serialized_start=450
  _globals['_REMOVERITEMRESPONSE']._serialized_end=506
  _globals['_INVENTORYSERVICE']._serialized_start=509
  _globals['_INVENTORYSERVICE']._serialized_end=826
# @@protoc_insertion_point(module_scope)
