# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub:
    """Serviço de Inventário de Heróis
    Permite que um herói (entidade já existente no domínio do RPG API)
    gerencie os itens que carrega: armas, poções, materiais, etc.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdicionarItem = channel.unary_unary(
                '/inventory.InventoryService/AdicionarItem',
                request_serializer=inventory__pb2.AdicionarItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.Item.FromString,
                _registered_method=True)
        self.ListarInventario = channel.unary_unary(
                '/inventory.InventoryService/ListarInventario',
                request_serializer=inventory__pb2.ListarInventarioRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventarioResponse.FromString,
                _registered_method=True)
        self.ConsultarItem = channel.unary_unary(
                '/inventory.InventoryService/ConsultarItem',
                request_serializer=inventory__pb2.ConsultarItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.Item.FromString,
                _registered_method=True)
        self.RemoverItem = channel.unary_unary(
                '/inventory.InventoryService/RemoverItem',
                request_serializer=inventory__pb2.RemoverItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.RemoverItemResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer:
    """Serviço de Inventário de Heróis
    Permite que um herói (entidade já existente no domínio do RPG API)
    gerencie os itens que carrega: armas, poções, materiais, etc.
    """

    def AdicionarItem(self, request, context):
        """Cadastra um novo item no inventário de um herói
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarInventario(self, request, context):
        """Lista todos os itens do inventário de um herói
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarItem(self, request, context):
        """Consulta um item específico pelo seu id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverItem(self, request, context):
        """Remove um item do inventário
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdicionarItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarItem,
                    request_deserializer=inventory__pb2.AdicionarItemRequest.FromString,
                    response_serializer=inventory__pb2.Item.SerializeToString,
            ),
            'ListarInventario': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarInventario,
                    request_deserializer=inventory__pb2.ListarInventarioRequest.FromString,
                    response_serializer=inventory__pb2.InventarioResponse.SerializeToString,
            ),
            'ConsultarItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarItem,
                    request_deserializer=inventory__pb2.ConsultarItemRequest.FromString,
                    response_serializer=inventory__pb2.Item.SerializeToString,
            ),
            'RemoverItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverItem,
                    request_deserializer=inventory__pb2.RemoverItemRequest.FromString,
                    response_serializer=inventory__pb2.RemoverItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService:
    """Serviço de Inventário de Heróis
    Permite que um herói (entidade já existente no domínio do RPG API)
    gerencie os itens que carrega: armas, poções, materiais, etc.
    """

    @staticmethod
    def AdicionarItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/AdicionarItem',
            inventory__pb2.AdicionarItemRequest.SerializeToString,
            inventory__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarInventario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ListarInventario',
            inventory__pb2.ListarInventarioRequest.SerializeToString,
            inventory__pb2.InventarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ConsultarItem',
            inventory__pb2.ConsultarItemRequest.SerializeToString,
            inventory__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/RemoverItem',
            inventory__pb2.RemoverItemRequest.SerializeToString,
            inventory__pb2.RemoverItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
