heroes = {
    "1": {
        "id": "1",
        "nome": "Gandalf",
        "classe": "Mago das Sombras",
        "nivel": 7,
        "avatar": "🧙",
        "status": "disponivel",
        "hp": 80,
        "max_hp": 100,
        "mp": 120,
        "max_mp": 120,
        "xp": 3400,
        "xp_next": 5000,
        "ouro": 250,
        "estatisticas": {
            "atk": 72,
            "def": 34,
            "spd": 55,
            "int": 91,
        },
        "missoes_ativas": [],
        "missoes_concluidas": [],
    },
    "2": {
        "id": "2",
        "nome": "Lyra",
        "classe": "Arqueira Ágil",
        "nivel": 5,
        "avatar": "🏹",
        "status": "disponivel",
        "hp": 70,
        "max_hp": 80,
        "mp": 60,
        "max_mp": 80,
        "xp": 1200,
        "xp_next": 3000,
        "ouro": 180,
        "estatisticas": {
            "atk": 65,
            "def": 20,
            "spd": 90,
            "int": 30,
        },
        "missoes_ativas": [],
        "missoes_concluidas": [],
    },
    "3": {
        "id": "3",
        "nome": "Thorn",
        "classe": "Paladino Guardião",
        "nivel": 6,
        "avatar": "⚔️",
        "status": "disponivel",
        "hp": 140,
        "max_hp": 150,
        "mp": 40,
        "max_mp": 60,
        "xp": 2200,
        "xp_next": 4000,
        "ouro": 300,
        "estatisticas": {
            "atk": 95,
            "def": 50,
            "spd": 25,
            "int": 15,
        },
        "missoes_ativas": [],
        "missoes_concluidas": [],
    },
    "4": {
        "id": "4",
        "nome": "Vesper",
        "classe": "Feiticeira das Sombras",
        "nivel": 5,
        "avatar": "🌙",
        "status": "disponivel",
        "hp": 60,
        "max_hp": 70,
        "mp": 140,
        "max_mp": 150,
        "xp": 1500,
        "xp_next": 3000,
        "ouro": 200,
        "estatisticas": {
            "atk": 30,
            "def": 15,
            "spd": 70,
            "int": 88,
        },
        "missoes_ativas": [],
        "missoes_concluidas": [],
    },
}
